core/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url
from core.views.people import (PeopleView, PersonDetailView, PersonEdit,
                               SalaryAddView, PersonAdd)
from core.views.people import (CandidateView, CandidateDetailView, CandidateEdit,
                               CandidateAdd)
from core.views.settings import (DashboardView, SettingsView, AccountCreateView,
                                 ExpenseCategoryAddView, ExpenseCategoryView,
                                 CurrencyAddView)
from core.views.transactions import (TransactionListView, IncomeAddView,
                                     ExpenseAddView, TransferAddView,
                                     CommissionAddView, PaymentAddView)
from core.views.inventory import (InventoryView, InventoryItemView, InventoryEdit,
                               InventoryAdd)

urlpatterns = patterns('core.views',
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    url(r'^settings/$', SettingsView.as_view(), name='settings'),

    url(r'^people/$', PeopleView.as_view(), name='people'),
    url(r'^people/(?P<pk>\d+)$', PersonDetailView.as_view(), name='person'),
    url(r'^people/add/$', PersonAdd.as_view(), name='add_person'),
    url(r'^people/edit/(?P<pk>\d+)$', PersonEdit.as_view(), name='edit_person'),

    url(r'^candidate/$', CandidateView.as_view(), name='candidates'),
    url(r'^candidate/(?P<pk>\d+)$', CandidateDetailView.as_view(), name='candidate'),
    url(r'^candidate/add/$', CandidateAdd.as_view(), name='add_candidate'),
    url(r'^candidate/edit/(?P<pk>\d+)$', CandidateEdit.as_view(), name='edit_candidate'),

    url(r'^salaries/add/$', SalaryAddView.as_view(), name='add_salary'),

    url(r'^accounts/add/$', AccountCreateView.as_view(), name='add_account'),

    url(r'^expense_categories/(?P<pk>\d+)$', ExpenseCategoryView.as_view(), 
        name='expence_category'),
    url(r'^expense_categories/add/$', ExpenseCategoryAddView.as_view(),
        name='add_expense_category'),

    url(r'^currencies/add/$', CurrencyAddView.as_view(), name='add_currency'),

    url(r'^transactions/$', TransactionListView.as_view(), name='transactions'),
    url(r'^income/add/$', IncomeAddView.as_view(), name='add_income'),
    url(r'^expense/add/$', ExpenseAddView.as_view(), name='add_expense'),
    url(r'^transfer/add/$', TransferAddView.as_view(), name='add_transfer'),
    url(r'^comission/add/(?P<pk>\d+)$', CommissionAddView.as_view(),
        name='add_comission'),
    url(r'^payment/add/(?P<pk>\d+)$', PaymentAddView.as_view(),
        name='add_payment'),

    url(r'^inventory/$', InventoryView.as_view(), name='inventory'),
    url(r'^inventory/(?P<pk>\d+)$', InventoryItemView.as_view(), name='inventory_item'),
    url(r'^inventory/add/$', InventoryAdd.as_view(), name='add_inventory'),
    url(r'^inventory/edit/(?P<pk>\d+)$', InventoryEdit.as_view(), name='edit_inventory'),

)

expensor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth',
                           app_name='auth')),
    url(r'_/', include('core.urls', namespace='core', app_name='core')),
    # Examples:
    # url(r'^$', 'expensor.views.home', name='home'),
    # url(r'^expensor/', include('expensor.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

core/models.py
# -*- encoding: utf-8 -*-
from __future__ import absolute_import
from datetime import datetime
from dateutil.relativedelta import relativedelta
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Sum
from django.db.models.query import QuerySet
from django.db.models.signals import post_save
from django.db import connection

from .managers import QuerySetManager


class Action(models.Model):
    name = models.CharField(max_length=128)


class People(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(db_index=True)
    phone = models.CharField(max_length=10)
        
    def __unicode__(self):
        return self.full_name

    class Meta:
        abstract = True
        ordering = ('first_name', 'last_name')

    @property
    def full_name(self):
        return u"{0.first_name} {0.last_name}".format(self)


class Person(People):
    position = models.CharField(max_length=256)
    notes = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(db_index=True, default=False)
    works_from = models.DateField(default=datetime.now)
    last_review = models.DateField(blank=True, null=True)
    hospital = models.IntegerField(blank=True, null=True)
    day_off = models.IntegerField(blank=True, null=True)

    objects = QuerySetManager()

    class QuerySet(QuerySet):

        def active(self):
            return self.filter(is_active=True)

        def inactive(self):
            return self.filter(is_active=False)



    def get_absolute_url(self):
        return reverse('core:person', kwargs={'pk': self.pk})


    @property
    def vacation(self):       
        period = datetime.now().date() - self.works_from        
        return (period.days/30)*1.75

    @property
    def next_review(self):
        if self.last_review:
            return self.last_review + relativedelta(months=6)

    @property
    def missed_review(self):
        if self.next_review < datetime.now().date():
            return True
        else:
            return False

    @property
    def salary(self):
        salaries = Salary.objects.filter(person=self,
                                         active_from__lte=datetime.now)
        if salaries.count() > 0:
            rv = salaries.latest('active_from')
        else:
            rv = Salary(amount=Decimal(0.00))
        return rv

    @property
    def salary_raise(self):
        salaries = Salary.objects.filter(person=self,
                                         active_from__lte=datetime.now)     
        if salaries.count() > 1:
            last = salaries[0].amount
            previous = salaries[1].amount
            rv = last-previous
        else:
            rv = 0
        return rv

    @property
    def payments(self):
        payments = []
        monthes = self.transactions.dates("bill_date", "month")
        for month in monthes:
            month_payments = self.transactions.filter(bill_date__month=month.month)            
            month_sum = month_payments.aggregate(Sum("amount"))['amount__sum']
            payments.append({'month': month.strftime("%Y %m"), 'month_sum': month_sum, 'payments': month_payments })
        payments = sorted(payments, key=lambda k: k['month'], reverse=True)
        return payments


class Candidate(People):

    QA = 1
    PYTHON = 2
    JS = 3
    HTML = 4
    DESIGN = 5

    division = (    
        (QA, 'QA'),
        (PYTHON, 'Python'),
        (JS, 'JS'),
        (HTML, 'Html/CSS'),
        (DESIGN, 'Designer')
    )

    REFUSED = 1
    NOT_ACCEPTED = 2
    ACCEPTED = 3
    BANNED = 4

    status = (
        (REFUSED, u'Отказали'),
        (NOT_ACCEPTED, u'Сделали оффер/не принял'),
        (ACCEPTED, u'Вышел на работу'),
        (BANNED, u'Бан-лист'),
    )

    division = models.IntegerField(choices=division, default=PYTHON)
    cv = models.URLField( blank=True, null=True)
    interview = models.URLField( blank=True, null=True)
    title = models.CharField(max_length=50,  blank=True, null=True)
    status = models.IntegerField(choices=status, blank=True, null=True)
    person = models.OneToOneField(Person, blank=True, null=True)

    objects = QuerySetManager()

    class QuerySet(QuerySet):

        def qa(self):
            return self.filter(division=Candidate.QA)

        def python(self):
            return self.filter(division=Candidate.PYTHON)

        def js(self):
            return self.filter(division=Candidate.JS)

        def html(self):
            return self.filter(division=Candidate.HTML)

        def designer(self):
            return self.filter(division=Candidate.DESIGN)

    def get_absolute_url(self):
        return reverse('core:candidate', kwargs={'pk': self.pk})


def create_person(sender, instance, **kwargs):
    if instance.status == Candidate.ACCEPTED and not instance.person:
        if instance.title:
            position = instance.title
        else:
            position = instance.division
            
        person = Person(
            first_name=instance.first_name,
            last_name=instance.last_name,
            email=instance.email,
            phone=instance.phone,
            position=position,
            works_from=datetime.now().date(),
            last_revie=datetime.now().date(),
            is_active=True
        )
        person.save()


post_save.connect(create_person, sender=Candidate, dispatch_uid="save_candidate_to_person")


class Salary(models.Model):
    person = models.ForeignKey(Person, related_name='salaries')
    amount = models.DecimalField(u'сумма', decimal_places=2, max_digits=10)
    created_at = models.DateTimeField(default=datetime.now)
    active_from = models.DateField(u'действует с', default=datetime.now)

    objects = QuerySetManager()

    class Meta:
        # get_latest_by = '-active_from'
        ordering = ('-active_from', )

    class QuerySet(QuerySet):

        def active(self):
            return self.filter(active_from__lte=datetime.now).latest()

    def __unicode__(self):
        return self.amount

    def get_absolute_url(self):
        return reverse('core:person', kwargs={'pk': self.person.pk})


class Account(models.Model):
    name = models.CharField(u'название', max_length=255)
    amount = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    comment = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    @property
    def balance(self):
        income = self.transactions.filter(direction=Transaction.DIRECTION_IN).\
            aggregate(Sum('amount'))['amount__sum'] or Decimal(0)
        expense = self.transactions.filter(direction=Transaction.DIRECTION_OUT).\
            aggregate(Sum('amount'))['amount__sum'] or Decimal(0)

        return income - expense


class ExpenseCategory(models.Model):
    name = models.CharField(u'название', max_length=255)
    direct_expense = models.BooleanField(u'прямой расход', default=True)
    is_transfer = models.BooleanField(u'перевод', default=False)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:expence_category', kwargs={'pk': self.pk})

    @classmethod
    def get_commission(cls):
        return cls.objects.get(direct_expense=True, is_transfer=True)

    @classmethod
    def get_transfer(cls):
        return cls.objects.get(direct_expense=False, is_transfer=True)

    @classmethod
    def get_payment(cls):
        return cls.objects.get(direct_expense=False, is_transfer=False)

    def get_total(self):
        total = self.transactions.aggregate(Sum('amount'))['amount__sum']
        return total if total is not None else 0

    def get_by_month(self):
        rv = self.transactions \
                 .extra({"month": connection.ops.date_trunc_sql('month', 'bill_date')}) \
                 .values("month") \
                 .annotate(sum=Sum("amount")) \
                 .order_by("month")
        for row in rv:
            row['month'] = '.'.join(row['month'].split('-')[:2])
        return rv


class Currency(models.Model):
    name = models.CharField(u'название', max_length=255, unique=True)
    ratio = models.FloatField(u'коэффициент', default=1)
    is_default = models.BooleanField(u'системная?', default=False)

    class Meta:
        verbose_name_plural = 'currencies'

    def __unicode__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if self.is_default:
            Currency.objects.filter(is_default=True).update(is_default=False)

        super(Currency, self).save(force_insert, force_update, using,
                                   update_fields)

    @classmethod
    def default(cls):
        return cls.objects.get(is_default=True)


class Transaction(models.Model):

    DIRECTION_IN = 1
    DIRECTION_OUT = 2

    DIRECTION_CHOICES = (
        (DIRECTION_IN, u'приход'),
        (DIRECTION_OUT, u'расход')
    )

    created_by = models.ForeignKey(User)
    account = models.ForeignKey(Account, verbose_name=u'счёт',
                                related_name='transactions')
    category = models.ForeignKey(ExpenseCategory, verbose_name=u'тип',
                                 related_name='transactions',
                                 null=True, blank=True)
    person = models.ForeignKey(Person, verbose_name=u'сотрудник', null=True,
                               blank=True, related_name='transactions')
    parent = models.ForeignKey('self', verbose_name=u'связанная', null=True,
                               blank=True, related_name='children')
    currency = models.ForeignKey(Currency, verbose_name=u'валюта')

core/views/base.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

__author__ = 'nimnull'


class AuthRequiredMixin(object):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuthRequiredMixin, self).dispatch(request, *args, **kwargs)

core/views/inventory.py
from django.views.generic import ListView, DetailView, edit
from core.forms import InventoryForm
from core.models import Inventory
from core.views.base import AuthRequiredMixin



class InventoryView(AuthRequiredMixin, ListView):
    model = Inventory

    def get_context_data(self, **kwargs):
        context = super(InventoryView, self).get_context_data(**kwargs)
        context['inventory_form'] = InventoryForm()
        return context


class InventoryItemView(DetailView):
    model = Inventory

    def get_context_data(self, **kwargs):
        inventory = kwargs['object']
        context = super(InventoryItemView, self).get_context_data(**kwargs)
        context['inventory_form'] = InventoryForm(instance=inventory)
        return context


class InventoryAdd(AuthRequiredMixin, edit.CreateView):
    model = Inventory
    form_class = InventoryForm


class InventoryEdit(AuthRequiredMixin, edit.UpdateView):
    model = Inventory
    form_class = InventoryForm

core/views/people.py
from django.views.generic import ListView, DetailView, edit
from core.forms import PersonForm, SalaryForm, PaymentForm, CandidateForm
from core.models import Person, Salary, Currency, Candidate
from core.views.base import AuthRequiredMixin



__author__ = 'nimnull'


class PeopleView(AuthRequiredMixin, ListView):
    model = Person

    def get_context_data(self, **kwargs):
        context = super(PeopleView, self).get_context_data(**kwargs)
        context['person_form'] = PersonForm()
        context['payment_form'] = PaymentForm()
        return context


class PersonDetailView(DetailView):
    model = Person

    def get_context_data(self, **kwargs):
        person = kwargs['object']
        context = super(PersonDetailView, self).get_context_data(**kwargs)
        context['salary_form'] = SalaryForm(initial={'person': person})
        context['payment_form'] = PaymentForm(initial={'currency': Currency.default(),
                                                       'amount_src': person.salary.amount})
        context['person_form'] = PersonForm(instance=person)
        return context


class PersonAdd(AuthRequiredMixin, edit.CreateView):
    model = Person
    form_class = PersonForm

class PersonEdit(AuthRequiredMixin, edit.UpdateView):
    model = Person
    form_class = PersonForm


class SalaryAddView(AuthRequiredMixin, edit.CreateView):
    model = Salary
    form_class = SalaryForm



class CandidateView(AuthRequiredMixin, ListView):
    model = Candidate

    def get_context_data(self, **kwargs):
        context = super(CandidateView, self).get_context_data(**kwargs)
        context['person_form'] = CandidateForm()
        return context


class CandidateDetailView(DetailView):
    model = Candidate

    def get_context_data(self, **kwargs):
        candidate = kwargs['object']
        context = super(CandidateDetailView, self).get_context_data(**kwargs)
        context['candidate_form'] = CandidateForm(instance=candidate)
        return context


class CandidateAdd(AuthRequiredMixin, edit.CreateView):
    model = Candidate
    form_class = CandidateForm


class CandidateEdit(AuthRequiredMixin, edit.UpdateView):
    model = Candidate
    form_class = CandidateForm


# def create_person(request, id):
#     pass

core/templates/core/account_form.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

core/templates/core/actions.html
{% extends "core/base_generic.html" %}

{% block container %}
    <div class="row">
        <div class="page-header">
            <h3>Welcome back</h3>
        </div>
    </div>
{% endblock container %}

core/templates/core/candidate_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th class="col-name">Имя</th>
            <th>Контакты</th>

            <th>CV</th>
            <th>Интервью</th>
            <th>Title</th>
            <th>Статус</th>


        </tr>
    </thead>
    <tbody>
        {% for person in persons %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td class="col-name">
                <a href="{% url 'core:candidate' pk=person.id %}" title="профиль">
                    {{ person.first_name }} {{ person.last_name }}
                </a>
            </td>
            <td>{{ person.email }}</td>

            {% if person.cv %}
            <td><a href="{{ person.cv }}">Link</a></td> 
            {% else %} 
            <td>-</td>      
            {% endif %}
            {% if person.interview %}
            <td><a href="{{ person.interview }}">Link</a></td> 
            {% else %} 
            <td>-</td>      
            {% endif %}
            <td>{{ person.title|default:"-" }}</td>
            <td>{{ person.get_status_display|default:"-" }}</td>


        </tr>
        {% endfor %}
    </tbody>
</table>

core/templates/core/direction.html
{% if direction == 1 %}
     <i class="icon-plus"></i>
{% else %}
     <i class="icon-minus"></i>
{% endif %}

core/templates/core/inventory_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th class="col-name">Название</th>
            <th>Описание</th>

            <th>Дата покупки</th>
            <th>Стоимость</th>
            <th>Тип</th>
            <th>Сотрудник</th>

        </tr>
    </thead>
    <tbody>
        {% for item in inventory %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td class="col-name">
                <a href="{% url 'core:inventory_item' pk=item.id %}" title="профиль">
                    {{ item.name }} 
                </a>
            </td>
            <td>{{ item.description }}</td>
           
            <td>{{ item.purchase_date }}</td>            
            <td>{{ item.price }}</td>
            <td>{{ item.get_inventory_type_display }}</td>


            {% if item.person %}
            <td><a href="{% url 'core:person' pk=item.person.id %}" title="профиль">
                                    {{ item.person }}</a></td> 
            {% else %} 
            <td>-</td>      
            {% endif %}
              
        </tr>
        {% endfor %}
    </tbody>
</table>

core/templates/core/person_detail.html
{% extends "core/inner_base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="span10"><h3>{{ person.full_name }} 
        <a data-action="add-payment" data-target="{% url 'core:add_payment' pk=person.id %}" href="#addPayment"><i class="icon-gift"></i></a>
        <a href="#editPerson" title="Редактировать сотрудника" data-toggle="modal"><i class="icon-pencil"></i></a></h3></div>
    </div>
    <div class="row">
        <div class="span3">
            <dl>
                <dt>Email</dt><dd>{{ person.email }}</dd>
                <dt>Телефон</dt><dd>{{ person.phone }}</dd>
                <dt>Позиция</dt><dd>{{ person.position }}</dd>
                <dt>С нами с</dt><dd>{{ person.works_from }}</dd>             
            </dl>
            <h4>Инвентарь</h4>    
            <ul class="styled">
                {% for item in person.inventory_set.all %}
                        <li><a href="{% url 'core:inventory_item' pk=item.id %}" 
                            data-toggle="tooltip" title="{{ payment.comment }}">{{ item.name }}</a></li> 
                {% endfor %} 
            </ul>
        </div>
        {% if user.is_staff %}
        <div class="span3">
            <h4>Зарплатный план: <small><a href="#addSalary" data-toggle="modal">изменить</a></small></h4>
            <ul class="unstyled">
                {% for salary in person.salaries.all %}
                    {% if salary == person.salary %}
                        <li><b>{{ salary.active_from }} &ndash; {{ salary.amount }}</b> — сейчас</li>
                    {% else %}
                        <li>{{ salary.active_from }} &ndash; {{ salary.amount }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="span3">
            <h4>Выплаты:</h4>
            {% for month in person.payments %}
                <h5>{{ month.month }}, Сумма: {{ month.month_sum }}</h5>
                <ul class="styled">
                    {% for payment in month.payments %}
                        <li>{{ payment.bill_date }} &mdash; <a href="#" data-toggle="tooltip" title="{{ payment.comment }}">{{ payment.amount }}</a></li> 
                    {% endfor %} 
                </ul>
            {% endfor %}

            {% comment %}
            <ul class="unstyled">
                {% for transaction in person.transactions.all %}
                <li>{{ transaction.bill_date }} &mdash; <a href="#" data-toggle="tooltip" title="{{ transaction.comment }}">${{ transaction.amount }}</a></li>
                {% endfor %}
            </ul>
            {% endcomment %}
        </div>
        {% else %}
            <div class="span3">Отдам кота, недорого!</div>
        {% endif %}
    </div>
{% endblock content %}

{% block modals %}
    <div class="modal hide fade" id="addSalary">
        <form class="form-horizontal" action="{% url 'core:add_salary' %}" method="POST">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Изменить ставку</h3>
        </div>
        <div class="modal-body">
                {% csrf_token %}
                {% for hidden in salary_form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in salary_form.visible_fields %}
                <div class="control-group">
                    <label class="control-label" for="inputEmail">{{ field.label_tag }}</label>
                    <div class="controls">{{ field }}</div>
                </div>
                {% endfor %}
        </div>
        <div class="modal-footer">
            <a href="#" data-dismiss="modal" class="btn">Отменить</a>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
        </form>
    </div>

    {% with action_id='addPayment' action_url='core:people' action_title='Внести з/п' action_form=payment_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}


    {% with action_id='editPerson' action_url='core:edit_person' person_id=person.id title='Редактировать сотрудника' action_form=person_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}  


{% endblock modals %}


{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/payment_form.js' %}"></script>
{% endblock extra_js %}

core/templates/core/person_form.html
{% extends "core/inner_base.html" %}

{% block content %}
    <form method="POST" action=".">
        {% csrf_token %}
    <ul class="unstyled">
        {{ form.as_ul }}
        <li><button class="btn" type="submit">Добавить</button></li>
    </ul>
    </form>
{% endblock content %}

core/templates/core/transaction_list.html
{% extends "core/inner_base.html" %}

{% block content %}
    <div class="row">
        <div class="span10">
            <h3>
                Транзакции
                <sup><small>
                    <a href="#newIncome" title="внести приход" data-toggle="modal"><i class="icon-plus"></i></a>
                    <a href="#newExpense" title="внести расход" data-toggle="modal"><i class="icon-minus"></i></a>
                    <a href="#newTransfer" title="перевод" data-toggle="modal"><i class="icon-retweet"></i></a>
                </small></sup>
            </h3>
            <table class="table table-striped" id='1'>
                <thead>
                    <tr>
                        <th>цель</th>
                        <th>дата</th>
                        <th>категория</th>
                        <th>сумма</th>
                        <th>валюта</th>
                        <th>счет</th>
                        <th></th>
                    </tr>
                </thead>                  
            {# </table> #}
               {% for month, transactions in transactions %}
                    <tr class="info">
                        <th colspan="7"><h4>{{ month|date:"m.Y" }}</h4></th>
                    </tr>
            {# <table class="table table-striped" >   #}
                        {% for trans in transactions %}
                            <tr>
                                <td>
                                    {% with direction=trans.direction %}{% include "core/direction.html" %}{% endwith %}
                                </td>
                                <td><a href="#" data-toggle="tooltip" title="{{ trans.comment }}">{{ trans.bill_date|date:"Y.m.d" }}</a></td>
                                <td>{{ trans.person|default:trans.category|default:"n/a" }}</td>
                                <td>{{ trans.amount }}</td>
                                <td>{{ trans.amount_src }} {{ trans.currency }}</td>
                                <td>{{ trans.account }}</td>
                                <td>
                                    <a data-action="add-commission" data-target="{% url 'core:add_comission' pk=trans.id %}" href="#addCommission">
                                        <i class="icon-shopping-cart"></i>
                                    </a>
                                </td>
                            </tr>
                            {% for child in trans.children.all %}
                                <tr style="font-size:0.8em;">
                                    <td></td>
                                    <td>
                                        {% with direction=child.direction %}{% include "core/direction.html" %}{% endwith %}
                                    </td>
                                    <td>{{ child.category|default:"n/a"|lower }}</td>
                                    <td>{{ child.amount }}</td>
                                    <td>{{ child.amount_src }} {{ child.currency}}</td>
                                    <td>{{ child.account }}</td>
                                    <td colspan="2"></td>
                                </tr>
                            {% endfor %}            
                        {% endfor %} 
            {# </table>   #}
                {% endfor %}



                {% comment %}
                {% for trans in object_list %}
                    <tr>
                        <td>
                            {% with direction=trans.direction %}{% include "core/direction.html" %}{% endwith %}
                        </td>
                        <td><a href="#" data-toggle="tooltip" title="{{ trans.comment }}">{{ trans.bill_date }}</a></td>
                        <td>{{ trans.person|default:trans.category|default:"n/a" }}</td>
                        <td>{{ trans.amount }}</td>
                        <td>{{ trans.amount_src }} {{ trans.currency }}</td>
                        <td>{{ trans.account }}</td>
                        <td>
                            <a data-action="add-commission" data-target="{% url 'core:add_comission' pk=trans.id %}" href="#addCommission">
                                <i class="icon-shopping-cart"></i>
                            </a>
                        </td>
                    </tr>
                    {% for child in trans.children.all %}
                        <tr style="font-size:0.8em;">
                            <td></td>
                            <td>
                                {% with direction=child.direction %}{% include "core/direction.html" %}{% endwith %}
                            </td>
                            <td>{{ child.category|default:"n/a"|lower }}</td>
                            <td>{{ child.amount }}</td>
                            <td>{{ child.amount_src }} {{ child.currency}}</td>
                            <td>{{ child.account }}</td>
                            <td colspan="2"></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                {% endcomment %}

            </table>
        </div>

    <div class="pagination">
        <span class="step-links">
            {% if transactions.has_previous %}
                <a href="?page={{ transactions.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}.
            </span>

            {% if transactions.has_next %}
                <a href="?page={{ transactions.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>


    </div>

{% endblock content %}


{% block modals %}
    <!-- expense form -->
    {% with action_id='newExpense' action_url='core:add_expense' action_title='Внести расход' action_form=expense_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}
    <!-- income form -->
    {% with action_id='newIncome' action_url='core:add_income' action_title='Внести приход' action_form=income_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}
    {% with action_id='newTransfer' action_url='core:add_transfer' action_title='Перевод' action_form=transfer_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}
    {% with action_id='addCommission' action_url='core:transactions' action_title='Комиссия' action_form=commission_form %}
        {% include "core/modal_form.html" %}
    {% endwith %}
{% endblock modals %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/commission_form.js"></script>
{% endblock extra_js %}